name: speak_up
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  dots_indicator: ^4.0.1
  dio: ^5.8.0+1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  video_player: ^2.9.5
  youtube_player_flutter: ^9.1.1
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.10.0
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  percent_indicator: ^4.2.5
  just_audio: ^0.9.46
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  image_picker: ^1.1.2
  flutter_sound: ^9.28.0
  pull_to_refresh: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_SemiCondensed-Regular.ttf
          weight: 400
    - family: Amsterdam
      fonts:
        - asset: assets/fonts/Amsterdam.ttf
